### ISSUE TITLE
Importer: Failed to invoke skopeo proxy

### ISSUE THREAD

**Issue by EliteAMDGamer** [ryanabx/fedora-cosmic-atomic#1]
When trying to run the image getting the error blow.

```
Operating System: Bazzite 39
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.7.5-201.fsync.fc39.x86_64 (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 980/PCIe/SSE2
```

```

sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/ryanabx/fedora-cosmic-atomic-silverblue:latest-amd64
Pulling manifest: ostree-unverified-registry:ghcr.io/ryanabx/fedora-cosmic-atomic-silverblue:latest-amd64
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: reading manifest latest-amd64 in ghcr.io/ryanabx/fedora-cosmic-atomic-silverblue: manifest unknown

```

**Comment by CristianArean** [comment]
Same issue here

**Comment by Juno-ko** [comment]
I'm having the same issue.

**Comment by ryanabx** [comment]
I'm working on packaging rpms for the fedora cosmic images, but I will see if I can run the CI again and fix the issue. My apologies

**Comment by ryanabx** [comment]
@EliteAMDGamer @CristianArean @Juno-ko try it now, I'm able to rebase my personal machine with no issue, I hope it's been resolved for you as well!

**Comment by EliteAMDGamer** [comment]
I was able to re-base as well. Thank you.

**Comment by ryanabx** [comment]
I'm going to close this issue, but if it crops up again, feel free to make a new issue or ping me in this issue!

**Comment by sameyepatch** [comment]
Hello, wanted to test cosmic and found myself in this same situation. I'm following the instructions and both the unsigned and signed image throw this error.

```
$ rpm-ostree rebase --reboot ostree-unverified-registry:ghcr.io/ublue-os/variant:40-amd64
Pulling manifest: ostree-unverified-registry:ghcr.io/ublue-os/variant:40-amd64
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: Requesting bearer token: invalid status code from registry 403 (Forbidden)
```

I'm using Fedora Silverblue 40 on a gnome-boxes vm with no software installed other than a browser using flatpak and fastfech in toolbox.

Also, the commands in the README throw errors because of the word VARIANT is in uppercase, when the command is expected in lowercase

**Comment by sameyepatch** [comment]
> The full correct command is:
> 
> ```
> rpm-ostree rebase ostree-unverified-registry:ghcr.io/ublue-os/cosmic-silverblue:40-amd64
> ```

This worked, thanks for the help (not the rebase, but I'll try again)
