### ISSUE TITLE
cosmic session doesn't start after login

### ISSUE THREAD

**Issue by poJilloy** [ryanabx/fedora-cosmic-atomic#34]
> thread 'main' panicked at greetd/src/session/worker.rs:200:12:unable to exec: EACCES
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thinkpad e450

**Comment by ryanabx** [comment]
Disable SELinux with the instructions in the readme

**Comment by ryanabx** [comment]
> > Disable SELinux with the instructions in the readme
> 
> 
> 
> I thought `sudo setenforce 0 && getenforce` disables SELinux, oopsie. Now it works. Thank you

I did it a different way, by manually editing `/etc/selinux/config` but someone made a pr to change those instructions. What did you end up doing to get it to work

**Comment by fiftydinar** [comment]
> I did it a different way, by manually editing `/etc/selinux/config` but someone made a pr to change those instructions. What did you end up doing to get it to work

`setenforce 0` just temporarily disables SELinux on current boot.

editing the selinux config is more correct for permanent approach.
