### ISSUE TITLE
COSMIC Files shows an error when deleting files

### ISSUE THREAD

**Issue by sungsphinx** [ryanabx/fedora-cosmic-atomic#42]
Using the latest `cosmic-base:40-amd64`

Error (had to type it manually since I can't copy it):

```
Delete {
  paths: [
    "/var/home/user/test",
  ],
}
Error during a `trash` operation: FileSystem { path: "/var/
home/.Trash-1000", source: Os { code: 13, kind: PermissionDenied,
message: "Permission denied" } }
```

I'm not sure if I should report to the upstream COSMIC Files repo, [`trash-rs`](https://github.com/Byron/trash-rs) or keep it here.

**Comment by ryanabx** [comment]
You can keep it open, we will close it when the upstream issue gets closed
